{
 "title": "Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "service", "label": "service", "query": { "query": "label_values(job)" } },
   { "name": "model_name", "label": "model_name", "query": { "query": "label_values(model_name)" } },
   {
    "name": "model_version",
    "label": "model_version",
    "query": {
     "query": "label_values({model_name=\"$model_name\"},model_version)"
    }
   },
   {
    "name": "time_range",
    "label": "time_range",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Service metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "API Trader Live",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "expr": "up{job=\"api_trader\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ML Signals Live",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "expr": "up{job=\"ml_signals\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Среднее время обработки запроса [Recent]",
   "type": "timeseries",
   "description": "Среднее время обработки запроса за выбранный период",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (req_url) (\n  rate(request_processing_seconds_sum{\n    job=\"$service\", \n    req_url!~\".*/metrics$|.*/healthcheck$\"\n  }[$time_range])\n)\n/\nsum by (req_url) (\n  rate(request_processing_seconds_count{\n    job=\"$service\", \n    req_url!~\".*/metrics$|.*/healthcheck$\"\n  }[$time_range])\n)\n",
     "legendFormat": "{{req_url}}"
    }
   ]
  },
  {
   "title": "Среднее время обработки запроса [All time]",
   "type": "timeseries",
   "description": "Среднее время обработки запроса за всё время",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (req_url) (request_processing_seconds_sum{\n    job=\"$service\", \n    req_url!~\".*/metrics$|.*/healthcheck$\"\n  }\n)\n/\nsum by (req_url) (request_processing_seconds_count{\n    job=\"$service\", \n    req_url!~\".*/metrics$|.*/healthcheck$\"\n  }\n)\n",
     "legendFormat": "{{req_url}}"
    }
   ]
  },
  {
   "title": "Скорость расчёта сигнала",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(signal_calculating_seconds_sum{model_version=\"${model_version:raw}\", model_name=\"$model_name\"}[$time_range])",
     "legendFormat": "Общее время расчёта сигнала"
    },
    {
     "expr": "rate(ml_predictions_time_sum{model_version=\"1.0.0\"}[5m])",
     "legendFormat": "Время предсказания ML модели"
    }
   ]
  },
  {
   "title": "Время исполнения ордера",
   "type": "timeseries",
   "description": "Складывается из:\n1. Запрос рыночных данных в api_trader\n2. Анализ рыночных данных в ml_signals\n3. Отправка запроса на исполнение заявки в api_trader",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(order_execution_seconds_sum{model_name=\"$model_name\", model_version=\"${model_version:raw}\"}[$time_range])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "ML metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "MAE Total",
   "type": "stat",
   "description": "Среднее значение MAE за всё время",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mae_sum{model_name=\"$model_name\", model_version=\"${model_version:raw}\"} / mae_count{model_name=\"$model_name\", model_version=\"${model_version:raw}\"}",
     "legendFormat": "{{signal}}"
    }
   ]
  },
  {
   "title": "MAE [All time]",
   "type": "timeseries",
   "description": "MAE за всё время для выбранной модели и версии",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "mae_sum{model_name=\"$model_name\", model_version=\"${model_version:raw}\"} / mae_count{model_name=\"$model_name\", model_version=\"${model_version:raw}\"}",
     "legendFormat": "{{signal}}"
    }
   ]
  },
  {
   "title": "MAE [All time]",
   "type": "timeseries",
   "description": "MAE, рассчитанная за всё время",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum by (model_name, model_version, signal) (mae_sum)\n/\nsum by (model_name, model_version, signal) (mae_count)",
     "legendFormat": "{{model_name}} v{{model_version}} {{signal}}"
    }
   ]
  },
  {
   "title": "MAE [Recent]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "sum by (model_name, model_version, signal) (\n  rate(mae_sum{\n  }[$time_range])\n)\n/\nsum by (model_name, model_version, signal) (\n  rate(mae_count{\n  }[$time_range])\n)",
     "legendFormat": "{{model_name}} v{{model_version}} {{signal}}"
    }
   ]
  }
 ]
}