mlflow:
  host: '130.193.58.232'
  port: '5000'
  experiment_name: 'crypto_sentiment'
dataset_name: 'flowfree/crypto-news-headlines'
embedder_name: 'cointegrated/LaBSE-en-ru'
texts_column_name: 'text'
target_column_name: 'label'
model_params:
  penalty: 'l1'